#!/usr/bin/env python3
from pathlib import Path
import sys
ROOT=Path(__file__).resolve().parents[1]
read=lambda p:(ROOT/p).read_text(encoding="utf-8")
app=read("internal/webui/static/app.js"); html=read("internal/webui/static/index.html"); css=read("internal/webui/static/style.css")
api=read("internal/api/server.go")+read("internal/api/team.go")+read("internal/api/assistant_orchestrator.go")+read("internal/api/provider_oauth.go")+read("internal/api/skills.go")+read("internal/api/local_ai_compute.go")
boot=read("internal/bootstrap/bootstrap.go")
assistant=read("internal/assistant/service.go"); orch=read("internal/projectorchestrator/service.go"); profiles=read("internal/agentprofile/service.go")
components=read("internal/localai/components.go")+read("internal/localai/components_omniroute.go")
catalog=read("internal/localai/catalog_bundled.go")+read("internal/localai/catalog_signed.go"); runtime_smoke=read("internal/localai/runtime_artifact_smoke_test.go")
compute=read("internal/localai/compute_policy.go"); oauth=read("internal/provideroauth/service.go"); skills=read("internal/skillcatalog/service.go")
setup=read("packaging/windows/setup/main.go"); desktop=read("packaging/windows/desktop/main.go"); workflow=read(".github/workflows/alpha3.1-stabilization.yml"); debpre=read("packaging/debian/preinst"); debpost=read("packaging/debian/postinst"); debbuild=read("scripts/build-ubuntu-deb.sh")
migration=read("migrations/0023_alpha31_assistant_orchestrator.sql")+read("migrations/0024_alpha31_agents_components.sql")+read("migrations/0025_alpha31_refinement.sql")+read("migrations/0026_alpha32_reliability.sql")+read("migrations/0027_alpha32_research_rounds.sql")
reliability=read("internal/storage/sqlite/migrate.go"); provision=read("internal/localai/provision.go"); installjobs=read("internal/localai/install_jobs.go"); localsvc=read("internal/localai/service.go"); teamsvc=read("internal/team/service.go"); teamtypes=read("internal/team/types.go"); teamworker=read("internal/teamworker/service.go"); infertransport=read("internal/inference/transport.go")+read("internal/inference/transport_openai.go")+read("internal/inference/transport_anthropic.go")
checks=[]
def ck(n,c): checks.append((n,bool(c)))
ck("Assistant and Project Orchestrator remain durable", "assistant_threads" in migration and "project_orchestrators" in migration and "type Service struct" in assistant and "type Service struct" in orch)
ck("Control Chat reuses real Assistant and Orchestrator routes", "a31RenderControlChat" in app and "/v1/assistant/threads/" in app and "/orchestrator/turns" in app)
ck("Agent Profiles remain durable and non-authoritative", "agent_profiles" in migration and "Profiles" in app and "DigiLogic Core" in app)
ck("expanded built-in profiles and Team presets are seeded", migration.count("INSERT OR IGNORE INTO agent_profiles") >= 20 and migration.count("INSERT OR IGNORE INTO team_presets") >= 4)
ck("Research Team integrity is persisted", "configuration_json" in migration and all(x in app for x in ["pin_models","independent_first_pass","full_provenance","preserve_failed_seats"]))
ck("Skills and tool bundles are durable", all(x in migration for x in ["skill_packages","skill_assignments","tool_bundles","agent_profile_tool_bundles"]) and "manifest.json" in skills)
ck("Skills packages quarantine before install", "quarantined" in skills and "package hash changed after quarantine" in skills)
ck("Nodes and Skills are top-level", '["nodes","⬡","Nodes"]' in app and '["skills","✦","Skills"]' in app)
ck("trusted Local AI bootstrap is build pinned", "BundledCatalogKeyID" in catalog and "verifyBundledCatalogPayload" in catalog and "EnsureBundled" in catalog)
ck("trusted Local AI includes CPU CUDA Vulkan runtimes", all(x in catalog for x in ['Backend: "cpu"','Backend: "cuda"','Backend: "vulkan"']))
ck("CUDA runtimes manage pinned companion libraries", all(x in catalog+provision+localsvc for x in ["Dependencies","cuda-runtime-12.4","cuda-runtime-12.8","runtimeInstallFingerprint","runtime.Dependencies"]))
ck("Clean runners execute the pinned managed CPU runtime", "TestBundledCPURuntimeArtifactSmoke" in runtime_smoke and "ONEPANE_RUNTIME_ARTIFACT_SMOKE" in workflow and "Managed runtime artifact smoke" in workflow and "needs.runtime_artifact_smoke.result" in workflow)
ck("Linux runtime archives allow only in-root relative symlinks", "safeArchiveSymlinkTarget" in provision and "tar.TypeSymlink" in provision and "../../outside" in runtime_smoke+read("internal/localai/provision_test.go") and 'ExecutableRel: "llama-b11430/llama-server"' in catalog)
ck("per-deployment compute policy is real", "deployment_compute_policies" in migration and "SetComputePolicy" in compute and "supervisor.Stop" in compute and "supervisor.Start" in compute)
ck("managed OmniRoute and external OmniRoute coexist", "installOmniRoute" in components and "startOmniRoute" in components and "omniQA(false)" in app and "omniQA(true)" in app)
ck("OAuth PKCE is real and Vault-backed", "code_challenge_method" in oauth and "S256" in oauth and "CreateProviderCredential" in oauth and "/v1/provider-oauth/callback" in api)
ck("Settings are canonical and inheritance scoped", all(x in app for x in ["Defaults for new Workspaces","Models & Compute","Providers & Auth","Nodes & Federation","Agents & Research","Skills & Tools"]) and "Existing Workspaces are never changed here" in app)
ck("Operations Activity Health Recovery Logs are functional", all(x in app for x in ["a31OperationsActivity","a31OperationsHealth","a31RecoveryContent","a31ToggleLogs"]))
ck("component layout is pointer-resizable without mutation rerender", "a31BindLayout" in app and "data-pw-resize" in app and "data-op-resize" in app)
ck("Tour uses isolated focus panes", "tour-pane-top" in app and "bottom-center" in app and ".tour-spotlight" in css)
ck("Windows static assets remain canonical", "cmp internal/webui/static/app.js packaging/windows/desktop/static/app.js" in workflow)
ck("Windows and Ubuntu packages remain CI outputs", "Build Windows x64 installer" in workflow and "Build Ubuntu amd64 package" in workflow)
ck("native Windows UI-ready smoke contract remains", "onepane-ui-ready|" in app and "ui-ready.txt" in desktop and "Assert-NativeUIReady" in workflow)
ck("Windows setup remains noninteractive-test capable", all(x in setup for x in ["--silent","--no-launch","--skip-optional-runtime"]))
ck("Windows upgrades retain and restore previous application payload on failed health", all(x in setup for x in ["capturePayloadRollback","rollback.Restore()","rollbackArmed","previous OnePane application payload restored"]) and "resp.StatusCode < 300" in setup)
ck("Ubuntu upgrades retain previous binary and activate recovery override on failed health", all(x in debpre+debpost+debbuild for x in ["package-upgrade","PENDING_ROLLBACK","ROLLBACK_DROPIN","activate_previous_binary","packaging/debian/preinst"]))
ck("Alpha upgrades create validate and auto-restore a durable rollback point", all(x in reliability for x in ["VACUUM INTO","pre-migration backup preserved","PRAGMA quick_check","type MigrationError struct","RestoreMigrationBackup","verifyDatabaseFile"]) and "errors.As(err, &migrationErr)" in boot and "sqlite.RestoreMigrationBackup" in boot)
ck("managed downloads resume durable partial artifacts", all(x in provision for x in ['dest + ".partial"','Header.Set("Range"','StatusPartialContent','StatusRequestedRangeNotSatisfiable','existingDownload','markResumableDownload','isResumableDownloadError']) and "markInstallJobInterrupted" in installjobs and "!isResumableDownloadError(err)" in localsvc)
ck("Research sessions freeze immutable manifests", all(x in migration+teamsvc for x in ["team_session_manifests","snapshot_sha256","SessionSnapshot","manifest_sha256"]))
ck("Research seats pin one resolved candidate across retries", "team_session_seat_bindings" in migration and "IncludeCandidateIDs" in teamworker and "BindSeat" in teamworker and "seat_binding_candidate_id" in teamworker)
ck("Research first pass can remain independent and complete", "ResearchPhaseIndependent" in teamworker and "m.RoundNumber >= turnRound" in teamworker and "RequireAllSeats" in teamsvc)
ck("Research Council advances automatic multi-round phases", all(x in teamworker+teamsvc+teamtypes for x in ["advanceResearchSessions","ResearchPhaseIndependent","ResearchPhaseCritique","ResearchPhaseSynthesis","CritiqueRounds","ResearchTotalRounds"]) and 'json:"critique_rounds"' in teamtypes and "a32CritiqueRounds" in app)
ck("Research provider failures pause the same round", all(x in teamworker+teamsvc for x in ["pauseResearch","PauseResearchRound","paused_for_deliberation","retry_after","attempt_count"]) and "round_number" in migration)
ck("Research paused rounds support manual same-round retry", "/v1/team-sessions/{sessionID}/research/retry" in api and "RetryResearchRound" in teamsvc and "Retry this round" in app and "Research Council resumed on the same round" in app)
ck("Research critique hides same-round outputs and anonymizes peers", "m.RoundNumber >= turnRound" in teamworker and "researchAuthorAlias" in teamworker and "AnonymizedCrossCritique" in teamworker)
ck("Research rate limits preserve provider retry time", "retryAfterMillis" in infertransport and infertransport.count("RetryAfterMS = retryAfterMillis") >= 2)
ck("Research manifest provenance is readable", "/v1/team-sessions/{sessionID}/manifest" in api and "getTeamSessionManifest" in api)
ck("Research provenance is presented in Inspector", all(x in app for x in ["A32_RESEARCH_INSPECTOR","Research Integrity","Bound candidate","Manifest SHA-256","/team-session","/manifest"]))
ck("Research Team configuration member fetch is ordered safely", app.index("const teamID=team.id||team.ID") < app.index("members=await apiRequest(`/v1/teams/${encodeURIComponent(teamID)}/members`)"))
failed=[n for n,o in checks if not o]
for n,o in checks: print(f"[{'PASS' if o else 'FAIL'}] {n}")
if failed:
 print(f"\nALPHA 3.1 PRODUCT CONTRACT: {len(failed)} CHECK(S) FAILED",file=sys.stderr)
 for n in failed: print(" - "+n,file=sys.stderr)
 sys.exit(1)
print(f"\nALPHA 3.1 PRODUCT CONTRACT: ALL {len(checks)} CHECKS PASSED")
